version: '2'
services:
  zookeeper:
    image: debezium/zookeeper:1.6
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: debezium/kafka:1.6
    ports:
     - 9092:9092
     - 9094:9094
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
     - KAFKA_ZOOKEEPER_CONNECT= zookeeper:2181
     - KAFKA_LISTENERS= INTERNAL://kafka:9092,OUTSIDE://kafka:9094
     - KAFKA_ADVERTISED_LISTENERS= INTERNAL://kafka:9092,OUTSIDE://localhost:9094
     - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP= INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
     - KAFKA_INTER_BROKER_LISTENER_NAME= INTERNAL
  mongodb:
    image: debezium/example-mongodb:1.6
    hostname: mongodb
    ports:
     - 27017:27017
    environment:
     - MONGODB_USER=debezium
     - MONGODB_PASSWORD=dbz
  connect:
    image: debezium/connect:1.6
    ports:
     - 8083:8083
    links:
     - kafka
     - mongodb
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
     - "9000:9000"
    environment:
     KAFKA_BROKERCONNECT: "kafka:9092"
     JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
     - "kafka"